DROP DATABASE IF EXISTS EMPLOYEE_db;
CREATE DATABASE EMPLOYEE_db;

USE EMPLOYEE_db;

CREATE TABLE deaprtment (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  naame VARCHAR(30) NOT NULL
);

CREATE TABLE rolee (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL,
    department_id INT,
    FOREIGN KEY (department_id)
    REFERENCES department(id)
    ON DELETE SET NULL
);

CREATE TABLE employee (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,

  rolee_id INT,
  FOREIGN KEY (rolee_id)
  REFERENCES rolee(id)
  ON DELETE SET NULL

  manager_id INT,
  FOREIGN KEY (manager_id)
  REFERENCES manager(id)
  ON DELETE SET NULL
)
